version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task_management
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    working_dir: /app/task_management_api
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://postgres:postgres@db:5432/task_management
      PORT: 3000
    ports:
      - '3000:3000'
    depends_on:
      - db
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    working_dir: /app/task_management_front
    environment:
      NODE_ENV: production
      REACT_APP_API_URL: http://localhost:3000/v1
    ports:
      - '3001:3000'
    depends_on:
      - backend
volumes:
  db_data:
